#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1" --quiet ||
(
    echo -e "\n❌ Please check commit message format! \n"
    false;
)

echo -e "✅ Commit message format correct! \n"